 package com.payflow.service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.payflow.entity.Transaction;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;

@Service
public class PdfReceiptService {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a");

    public byte[] generateReceipt(Transaction txn) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try (PdfWriter writer = new PdfWriter(baos);
             PdfDocument pdf = new PdfDocument(writer);
             Document document = new Document(pdf)) {

            document.add(new Paragraph("PayFlow")
                    .setBold()
                    .setFontSize(22)
                    .setFontColor(new com.itextpdf.kernel.colors.DeviceRgb(91, 61, 214)));

            document.add(new Paragraph("Payment Receipt")
                    .setFontSize(14)
                    .setMarginBottom(20));

            boolean success = txn.getStatus() == Transaction.TransactionStatus.SUCCESS;
            Paragraph status = new Paragraph(success ? "SUCCESS" : txn.getStatus().name())
                    .setBold()
                    .setFontColor(success ? ColorConstants.GREEN : ColorConstants.RED)
                    .setFontSize(16);
            document.add(status);

            Table table = new Table(UnitValue.createPercentArray(new float[]{1, 2}))
                    .useAllAvailableWidth()
                    .setMarginTop(15);

            addRow(table, "Reference ID", txn.getReferenceId());
            addRow(table, "Date & Time", txn.getCreatedAt().format(FORMATTER));
            addRow(table, "Amount", "\u20B9 " + txn.getAmount().toString());
            addRow(table, "Type", txn.getTransactionType().name());
            addRow(table, "From (VPA)", nullSafe(txn.getSenderVpa()));
            addRow(table, "To (VPA)", nullSafe(txn.getReceiverVpa()));
            if (txn.getNote() != null && !txn.getNote().isBlank()) {
                addRow(table, "Note", txn.getNote());
            }
            if (txn.getFailureReason() != null) {
                addRow(table, "Failure Reason", txn.getFailureReason());
            }

            document.add(table);

            document.add(new Paragraph(
                    "\nThis is a demo receipt generated by PayFlow for educational purposes only. " +
                            "It does not represent a real financial transaction.")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(40));
        }

        return baos.toByteArray();
    }

    private void addRow(Table table, String label, String value) {
        table.addCell(new Cell().add(new Paragraph(label).setBold()).setBorder(null));
        table.addCell(new Cell().add(new Paragraph(value == null ? "-" : value)).setBorder(null));
    }

    private String nullSafe(String value) {
        return value == null ? "PayFlow Wallet" : value;
    }
}
